[package]
name = "st_link"
version = "0.1.0"
authors = ["Martin Thuranira <38188355+MartinThuranira@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
